### ISSUE TITLE
Khắc phục lỗi xóa bài tập trong module 5

### ISSUE THREAD

**Issue by quanhoang-pm** [MIMPython/MIMPython2023-Assignment#76]
Tới thời điểm hiện tại, các bạn trong lớp MIMPython đều đã hoàn thành việc nộp bài trong một số pull request ví dụ như #72, #71, #70, #67, #65.

Tuy nhiên tính đến commit [03d2bd4](https://github.com/MIMPython/MIMPython2023-Assignment/commit/03d2bd48ee29972346f3f41c8818822aceede747) thì bài làm của 5 bạn không còn xuất hiện trong repository này nữa.

Sau quá trình tìm hiểu, nguyên nhân cho việc này có lẽ xuất phất từ commit https://github.com/MIMPython/MIMPython2023-Assignment/commit/3e0611358c077e035cf7c86221b47ee1f0aaf6da của @ThuyBachDuong.

Nhờ @ThuyBachDuong tag 5 bạn có bài làm bị mất vào issue này.

5 bạn này cần tạo lại pull request để nộp lại bài tập, chú ý rằng
- Trong mô tả của pull request, reference tới issue này (như cách reference ở đoạn trên cùng)
- Gắn label phù hợp, đặt reviewer là @ThuyBachDuong 

@ThuyBachDuong chịu trách nhiệm merge các pull request và đóng issue này khi toàn bộ bài tập module 5 xuất hiện ở repo.

**Comment by ThuyBachDuong** [comment]
Nhờ các bạn @imtmchau @thimenni @mquangdo @illgidgud @thnam19 thực hiện lại pull request đối với module05 nhé ạ.
Mình sẽ rút kinh nghiệm những việc liên quan đến commit [3e06113](https://github.com/MIMPython/MIMPython2023-Assignment/commit/3e0611358c077e035cf7c86221b47ee1f0aaf6da), xin lỗi vì đã làm ảnh hưởng mọi người ạ

**Comment by mquangdo** [comment]
@ThuyBachDuong không có vấn đề gì cả Nhật Anh ạ

**Comment by ThuyBachDuong** [comment]
@quanhoang-pm Hiện tại đã có 4 bạn tạo pull request và em đã review bài làm của các bạn. Tuy nhiên việc merge PR vào repository yêu cầu **_write access_** nên em chưa thực hiện được ạ.

**Comment by quanhoang-pm** [comment]
@ThuyBachDuong em có thực hiện được review với quyền hiện tại không? Nếu được thì em approve các pull request này, rồi tag anh vào để anh merge vào main nhé.
